plugins { id 'com.android.application' }
android {
 namespace 'org.ghcstudy.offline'
 compileSdk 35
 defaultConfig {
  applicationId 'org.ghcstudy.v141'
  minSdk 24
  targetSdk 35
  versionCode 142
  versionName '1.4.2'
 }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
