(function(){
'use strict';
var bank=window.GHC_GERMAN_VOCAB.entries, quiz=[], pos=0, right=0, answered=false;
var key='ghc-german-vocab-progress-v1';
function escv(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function shuffled(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
function options(q){var pool=bank.filter(function(x){return x.group===q.group&&x.english!==q.english});var distract=shuffled(pool).slice(0,3);if(distract.length<3)distract=distract.concat(shuffled(bank.filter(function(x){return x.group!==q.group})).slice(0,3-distract.length));return shuffled([q].concat(distract))}
function begin(group){quiz=shuffled(bank.filter(function(x){return !group||x.group===group}));pos=0;right=0;show()}
function show(){if(pos>=quiz.length){var prev={};try{prev=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){};prev.sessions=(prev.sessions||0)+1;prev.correct=(prev.correct||0)+right;prev.total=(prev.total||0)+quiz.length;localStorage.setItem(key,JSON.stringify(prev));app.innerHTML='<section class="hero"><h1>German Vocabulary</h1><p>Finished: '+right+' / '+quiz.length+' correct.</p><button class="btn main" id="vocabHome">Back to Quiz Mode</button></section>';document.getElementById('vocabHome').onclick=function(){view='study';mode='home';render()};return}
answered=false;var q=quiz[pos],choices=options(q);app.innerHTML='<button class="backlink" id="vocabBack">← Quiz Mode</button><section class="hero"><h1>German Vocabulary</h1><p>'+escv(q.group)+' · '+(pos+1)+' / '+quiz.length+' · '+right+' correct</p></section><div class="card" style="padding:18px"><h2 style="margin:0 0 14px">'+escv(q.word)+'</h2><p>What does this German hunting term mean?</p><div id="vocabChoices" style="display:grid;gap:10px">'+choices.map(function(c,i){return '<button class="btn secondary" style="white-space:normal;text-align:left" data-vocab="'+i+'">'+escv(c.english)+'</button>'}).join('')+'</div><div id="vocabExplanation" style="margin-top:14px"></div></div>';document.getElementById('vocabBack').onclick=function(){view='study';mode='home';render()};Array.prototype.forEach.call(document.querySelectorAll('[data-vocab]'),function(b){b.onclick=function(){if(answered)return;answered=true;var choice=choices[Number(b.getAttribute('data-vocab'))],ok=choice.english===q.english;if(ok)right++;Array.prototype.forEach.call(document.querySelectorAll('[data-vocab]'),function(el){el.disabled=true});var image='';var visualNames={'Rehwild':'roe_buck_summer','Muffelwild':'mouflon'};var v=visualNames[q.word];if(v&&window.GHC_STUDY_IMAGES&&window.GHC_STUDY_IMAGES[v])image='<img style="width:100%;max-height:220px;object-fit:contain" src="'+escv(window.GHC_STUDY_IMAGES[v].src)+'" alt="'+escv(q.word)+'">';document.getElementById('vocabExplanation').innerHTML='<h3>'+(ok?'Correct':'Incorrect')+'</h3><p><b>'+escv(q.word)+' — '+escv(q.english)+'</b></p><p>'+escv(q.explanation)+'</p>'+image+'<button class="btn main" id="vocabNext">Next →</button>';document.getElementById('vocabNext').onclick=function(){pos++;show()}}})}
var old=renderHome;
renderHome=function(){old();var hero=app.querySelector('.hero')||app;var b=document.createElement('button');b.className='btn main';b.textContent='German Vocabulary Quiz';b.style.margin='10px 0';b.onclick=function(){var groups=['All words'].concat(Array.from(new Set(bank.map(function(x){return x.group}))));app.innerHTML='<button class="backlink" id="vocabBack">← Quiz Mode</button><section class="hero"><h1>German Vocabulary Quiz</h1><p>German word → English meaning. Four related choices; explanations after each answer.</p></section><div class="study-cat-grid">'+groups.map(function(g,i){return '<button class="card study-cat" data-vocab-group="'+i+'"><h3>'+escv(g)+'</h3><p>'+(i===0?bank.length:bank.filter(function(x){return x.group===g}).length)+' words</p></button>'}).join('')+'</div>';document.getElementById('vocabBack').onclick=function(){view='study';mode='home';render()};Array.prototype.forEach.call(document.querySelectorAll('[data-vocab-group]'),function(el){el.onclick=function(){var n=Number(el.getAttribute('data-vocab-group'));begin(n?groups[n]:null)}})};hero.appendChild(b)};
})();